### ISSUE TITLE
Other repos

### ISSUE THREAD

**Issue by digilou** [accessibility/a11y-lists-of-lists#2]
Have you seen these repos?
- Heydon Pickering's [inclusive design checklist](https://github.com/Heydon/inclusive-design-checklist)
- [Accessible Components](https://github.com/scottaohara/accessible_components)
- [A11y Project](https://github.com/a11yproject/a11yproject.com)

Not sure if they're the types of lists you're looking for.

**Comment by cehfisher** [comment]
Yes we have and they are awesome! I'll check the current list and see if they need to be added still. Thanks much
