### ISSUE TITLE
List of a11y ressources produced by the French government

### ISSUE THREAD

**Issue by access42** [accessibility/a11y-lists-of-lists#3]
Hi!

Great initiative.
We made a list of the official resources produced by the French government to promote the French General Accessibility Reference and raise awareness on digital accessibility and disability.

There are nearly 30 resources (some of then translated in English).

http://gta2017.access42.net/2/ressources/

We thought you might find it interesting and add it to your list of lists :)

**Comment by mgifford** [comment]
That's great. Thanks! Having resources in languages other than English is rather important!

**Comment by mgifford** [comment]
Added
